site_name: Neo4j To TigerGraph
site_url: https://github.com/dmccrearytg/neo4j-to-tigergraph
site_description: 'An intelligent agent that converts a running Neo4j database to a TigerGraph database.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccrearytg.github.io/neo4j-to-tigergraph'
repo_url: 'https://github.com/dmccrearytg/neo4j-to-tigergraph'
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - About: about.md
  - Build Steps: build-steps.md
  - Architecture: architecture.md
  - Sample Databases: sample-databases.md
  - Contact: contact.md

# edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/tg-logo-small.png
  favicon: img/favicon.ico
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
# extra:
#  analytics:
#    provider: google
#    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-BBR7MPK96Z